Remove duplicate crowd rest client
There are two rest clients in the pom.xml, which  worked in the past.
But now in Azure environment an initialization error occurs:
Caused by: java.lang.NoSuchMethodError: 'com.atlassian.crowd.service.client.AuthenticationMethod com.atlassian.crowd.service.client.ClientProperties.getAuthenticationMethod()'

This happens because two ClientProperties in the classpath exist but the wrong is chosen.
This fix removes the old rest client lib from crowd.